### ISSUE TITLE
Could not find a version that satisfies the requirement tensorflow==2.4.1

### ISSUE THREAD

**Issue by burf2000** [HaiderAbasi/SelfDrivingProject_MiniTesla#20]
When I try to install the requirements, it can no longer find tensorflow

**Comment by HaiderAbasi** [comment]
- You should list the environment you are trying to setup this project.

  > E.g, If you are trying to setup on Raspberry Pi make sure you have the correct OS and have installed required modules from the relevant requirements file.

  > ![Screenshot_20230906-115013](https://github.com/HaiderAbasi/SelfDrivingProject_MiniTesla/assets/49869365/de9565ec-d7b9-4c66-9c69-54038b9b35af)

**Comment by burf2000** [comment]
I now get ERROR: tensorflow-2.4.0-cp37-none-linux_armv7l.whl is not a supported wheel on this platform.

**Comment by burf2000** [comment]
This is a Raspberry Pi 3 with latest Raspberry OS, should I install ubuntu

**Comment by burf2000** [comment]
I have just reformatted this with the 64bit version of Raspberry PI OS and still does not work

(sdc_env) burf2000@picar:~/SelfDrivingProject_MiniTesla $ pip3 install -r requirements_pi.txt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple

ERROR: tensorflow-2.4.0-cp37-none-linux_armv7l.whl is not a supported wheel on this platform.

(sdc_env) burf2000@picar:~/SelfDrivingProject_MiniTesla $

**Comment by HaiderAbasi** [comment]
@noshluk2 Can you identify what might be the problem here? Is he using an older Raspberry PI or OS?

**Comment by burf2000** [comment]
I have a raspberry Pi 3, I tried the latest OS (32bit and 64bit). I think the issue is that Tensorflow 2.4.1 only works with Python 3.5-3.7 and has also moved to pip, 

the latest os has 3.9

**Comment by HaiderAbasi** [comment]
Yup, Change it to Buster OS or whichever that's python 3.7.
It's definitely the python version issue 

> This is confirmed when we look at the wheel we are installing
  -  tensorflow-2.4.0-cp37-none-linux_armv7l.whl
  > The "cp37" part indicates the Python version. It's also built for Linux systems with ARMv7 architecture.

**Comment by HaiderAbasi** [comment]
-  Marking as closed.as solution is highlighted.
   > Reopen if problem persists.
